web: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py bootstrap_admin && gunicorn config.wsgi --bind 0.0.0.0:$PORT
worker: celery -A config worker --loglevel=info
beat: celery -A config beat --loglevel=info
