# Generated by Django 4.2.13 on 2026-10-08 21:15

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_remove_document_verified_document_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_url', models.URLField(blank=True, verbose_name='Image de couverture (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Durée (min)')),
                ('question_count', models.PositiveSmallIntegerField(default=40, verbose_name='Nombre de questions')),
                ('pass_score', models.PositiveSmallIntegerField(default=88, help_text='ETG officiel : 35/40 = 87,5 %', verbose_name='Score de réussite (%)')),
                ('topics', models.CharField(blank=True, max_length=300, verbose_name='Thèmes (séparés par des virgules, vide = tous)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_demo', models.BooleanField(default=False, verbose_name="Série d'essai gratuite (sans compte)")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Examen blanc',
                'verbose_name_plural': 'Examens blancs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('video_url', models.URLField(blank=True, verbose_name='Vidéo (YouTube, Vimeo ou fichier .mp4)')),
                ('content_md', models.TextField(blank=True, verbose_name='Contenu (Markdown : titres, listes, images, blocs de code ```lang)')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='Durée estimée (min)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('pass_score', models.PositiveSmallIntegerField(default=80, verbose_name='Score de réussite (%)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lms.lesson')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Chapitre de démonstration (accès libre sans compte)')),
                ('unlock_threshold', models.PositiveSmallIntegerField(default=80, help_text='0 = pas de verrou', verbose_name='Score minimal au quiz pour débloquer la section suivante (%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lms.course')),
            ],
            options={
                'verbose_name': 'Section',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Score (%)')),
                ('passed', models.BooleanField()),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lms.section'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SINGLE', 'QCM — une seule bonne réponse'), ('MULTI', 'QCM — plusieurs bonnes réponses'), ('TRUE_FALSE', 'Vrai / Faux'), ('SHORT', 'Réponse courte'), ('CODE', 'Saisie de code')], default='SINGLE', max_length=12, verbose_name='Type')),
                ('text_md', models.TextField(verbose_name='Énoncé (Markdown)')),
                ('explanation_md', models.TextField(blank=True, verbose_name='Explication affichée après correction (Markdown)')),
                ('expected_answer', models.CharField(blank=True, max_length=500, verbose_name='Réponse attendue (réponse courte / code)')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=60, verbose_name="Thème (banque d'examen)")),
                ('in_exam_bank', models.BooleanField(default=False, verbose_name="Dans la banque d'examens blancs")),
                ('is_published', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(blank=True, help_text="Vide = question de la banque d'examen uniquement", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to=lms.models.lesson_asset_upload)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='lms.lesson')),
            ],
            options={
                'verbose_name': 'Image / schéma',
                'verbose_name_plural': 'Images / schémas',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.section'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('SUBMITTED', 'Terminé'), ('EXPIRED', 'Temps écoulé')], default='IN_PROGRESS', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('correct_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Proposition')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Bonne réponse')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lms.question')),
            ],
            options={
                'verbose_name': 'Proposition',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'slug')},
        ),
    ]
