# Generated by Django 4.2.13 on 2026-10-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_etg_validation'),
        ('lms', '0002_seed_demo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Vide = tirage aléatoire simple', verbose_name='Répartition par thème (code → nombre de questions)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='seconds_per_question',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Secondes par question (0 = chrono global uniquement)'),
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, choices=[('L', 'L — La circulation routière'), ('C', 'C — Le conducteur'), ('R', 'R — La route'), ('U', 'U — Les autres usagers'), ('D', 'D — Réglementation générale'), ('P', 'P — Prendre et quitter son véhicule'), ('M', 'M — Éléments mécaniques et de sécurité'), ('S', 'S — Équipements de sécurité des véhicules'), ('E', "E — L'environnement"), ('A', 'A — Premiers secours')], help_text='Lettre du thème ETG (L, C, R, U, D, P, M, S, E, A)', max_length=2, verbose_name='Thème officiel'),
        ),
        migrations.CreateModel(
            name='StudyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_time', to='core.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'day')},
            },
        ),
    ]
