# Generated by Django 4.2.13 on 2026-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_official_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name="Illustration (URL de l'image)"),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Vidéo explicative (YouTube, Vimeo, .mp4 / .webm)'),
        ),
    ]
