# Generated by Django 4.2.13 on 2026-10-06 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Heures incluses')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix TTC (€)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': "Achat d'heures"},
        ),
        migrations.AddField(
            model_name='package',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note interne (ex: virement reçu le …)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('COMPLETED', 'Payé — heures créditées'), ('FAILED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='core.offer'),
        ),
    ]
