# Generated by Django 4.2.13 on 2026-10-08 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_slot_unique_together_slot_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Maîtriser le maniement du véhicule dans un trafic faible ou nul'), (2, 'Appréhender la route et circuler dans des conditions normales'), (3, 'Circuler dans des conditions difficiles et partager la route'), (4, 'Pratiquer une conduite autonome, sûre et économique')])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compétence REMC',
                'ordering': ['group', 'order', 'code'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bilan de leçon'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'Achat / souscription'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='remc_skills',
        ),
        migrations.AddField(
            model_name='offer',
            name='billing_type',
            field=models.CharField(choices=[('ONE_TIME', 'Paiement unique'), ('MONTHLY', 'Abonnement mensuel'), ('INSTALLMENTS_3', 'En 3 fois'), ('INSTALLMENTS_4', 'En 4 fois')], default='ONE_TIME', max_length=20, verbose_name='Type de facturation'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('PERMIS_B', 'Permis B'), ('CODE', 'Code seul'), ('PERFECTIONNEMENT', 'Perfectionnement / remise en selle'), ('RECHARGE', "Recharge d'heures")], default='PERMIS_B', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='offer',
            name='for_code_status',
            field=models.CharField(choices=[('ANY', 'Indifférent'), ('TO_PASS', 'Code à passer'), ('OBTAINED', 'Code obtenu')], default='ANY', max_length=10, verbose_name='Cible : statut du code'),
        ),
        migrations.AddField(
            model_name='offer',
            name='for_level',
            field=models.CharField(choices=[('ANY', 'Indifférent'), ('BEGINNER', 'Débutant'), ('REFRESH', 'Révision / remise à niveau')], default='ANY', max_length=10, verbose_name='Cible : niveau'),
        ),
        migrations.AddField(
            model_name='offer',
            name='gearbox',
            field=models.CharField(choices=[('ANY', 'Indifférent'), ('AUTO', 'Boîte automatique'), ('MANUAL', 'Boîte manuelle')], default='ANY', max_length=10, verbose_name='Boîte'),
        ),
        migrations.AddField(
            model_name='offer',
            name='includes_lms',
            field=models.BooleanField(default=False, verbose_name='Accès cours de code / quiz / examens blancs'),
        ),
        migrations.AddField(
            model_name='offer',
            name='validity_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Validité (mois, vide = illimité)'),
        ),
        migrations.AddField(
            model_name='package',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de validité'),
        ),
        migrations.AddField(
            model_name='slot',
            name='hours_debited',
            field=models.BooleanField(default=False, verbose_name='Heures débitées'),
        ),
        migrations.AddField(
            model_name='slot',
            name='hours_refunded',
            field=models.BooleanField(default=False, verbose_name='Heures re-créditées (dérogation)'),
        ),
        migrations.AddField(
            model_name='slot',
            name='refund_note',
            field=models.TextField(blank=True, verbose_name='Justificatif de dérogation'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lms_access',
            field=models.BooleanField(default=False, verbose_name='Accès cours de code / quiz'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lms_access_until',
            field=models.DateField(blank=True, null=True, verbose_name="Accès LMS jusqu'au (vide = illimité)"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='attended',
            field=models.BooleanField(default=True, verbose_name='Élève présent'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instructor_notes',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='voice_memo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heures de conduite incluses'),
        ),
        migrations.AlterField(
            model_name='package',
            name='hours_purchased',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('COMPLETED', 'Payé — accès et heures crédités'), ('FAILED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BOOKED', 'Réservé'), ('CANCELLED', 'Annulé'), ('CANCELLED_LATE', 'Annulé hors délai'), ('NO_SHOW', 'Absent')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.lesson')),
            ],
            options={
                'verbose_name': 'Avis sur le moniteur',
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_COVERED', 'Non abordé'), ('IN_PROGRESS', 'En cours'), ('ACQUIRED', 'Acquis')], default='IN_PROGRESS', max_length=20)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.competency')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.lesson')),
            ],
            options={
                'verbose_name': 'Évaluation de compétence',
                'unique_together': {('lesson', 'competency')},
            },
        ),
    ]
