# Generated by Django 4.2.13 on 2026-10-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_competencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone mobile (SMS)'),
        ),
    ]
