# Generated by Django 4.2.13 on 2026-10-08 18:24

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='gearbox',
            field=models.CharField(choices=[('AUTO', 'Boîte automatique'), ('MANUAL', 'Boîte manuelle'), ('BOTH', 'Les deux')], default='BOTH', max_length=10, verbose_name='Boîte enseignée'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='lessonrating',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Masqué (modération)'),
        ),
        migrations.AddField(
            model_name='lessonrating',
            name='reply',
            field=models.TextField(blank=True, verbose_name="Réponse de l'école"),
        ),
        migrations.AddField(
            model_name='package',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payé le'),
        ),
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gearbox', models.CharField(choices=[('AUTO', 'Boîte automatique'), ('MANUAL', 'Boîte manuelle'), ('BOTH', 'Les deux')], default='BOTH', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('diploma', models.FileField(upload_to=core.models._application_upload, verbose_name="Diplôme / autorisation d'enseigner")),
                ('driving_license', models.FileField(upload_to=core.models._application_upload, verbose_name='Permis de conduire')),
                ('business_doc', models.FileField(blank=True, upload_to=core.models._application_upload, verbose_name='Kbis / statut auto-entrepreneur')),
                ('status', models.CharField(choices=[('PENDING', 'À examiner'), ('APPROVED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature moniteur',
                'ordering': ['-created_at'],
            },
        ),
    ]
