# Generated by Django 4.2.13 on 2026-10-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('quantity_hours', models.FloatField(default=0)),
                ('amount_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('ISSUED', 'Émise — à régler'), ('PAID', 'Payée'), ('CANCELLED', 'Annulée')], default='ISSUED', max_length=10)),
                ('issued_at', models.DateField()),
                ('due_at', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-issued_at', '-id'],
            },
        ),
    ]
