# Generated by Django 4.2.13 on 2026-10-08 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_document_verified_document_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='zones',
            field=models.CharField(blank=True, help_text='Villes / quartiers, séparés par des virgules', max_length=255, verbose_name='Zones de prise en charge'),
        ),
        migrations.AddField(
            model_name='package',
            name='label',
            field=models.CharField(blank=True, max_length=150, verbose_name="Libellé (si pas d'offre)"),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Non précisé'), ('STRIPE', 'Carte bancaire (lien de paiement)'), ('CASH', 'Espèces'), ('CHECK', 'Chèque'), ('TRANSFER', 'Virement'), ('CPF', 'CPF'), ('FREE', 'Offert / régularisation')], default='', max_length=10, verbose_name='Mode de règlement'),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien de paiement'),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Dossier incomplet'), ('REGISTERED', 'Inscrit / NEPH en attente'), ('CODE', 'Code en cours'), ('DRIVING', 'Prêt pour la conduite'), ('EXAM', 'Examen réservé'), ('LICENSED', 'Permis obtenu'), ('ARCHIVED', 'Archivé')], default='INCOMPLETE', max_length=12, verbose_name='Statut du parcours'),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='status',
            field=models.CharField(choices=[('PENDING', 'À valider'), ('APPROVED', 'Validée'), ('REJECTED', 'Refusée')], default='APPROVED', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('BOOKING', 'Réservation'), ('CANCELLATION', 'Annulation'), ('LATE_CANCELLATION', 'Annulation tardive'), ('NO_SHOW', 'Absence'), ('REFUND', 'Re-crédit'), ('SLOT_MOVED', 'Créneau déplacé'), ('PAYMENT', 'Paiement'), ('HOURS_ADDED', 'Heures ajoutées'), ('APPLICATION', 'Candidature'), ('INSTRUCTOR', 'Moniteur'), ('LESSON', 'Bilan'), ('REMINDERS', 'Rappels'), ('DOCUMENT', 'Document'), ('STATUS', 'Statut élève'), ('MESSAGE', 'Message envoyé'), ('ABSENCE', 'Absence moniteur'), ('PLANNING', 'Planning'), ('TEAM', 'Équipe admin'), ('CONTRACT', 'Contrat'), ('LMS', 'Accès code'), ('PAYMENT_LINK', 'Lien de paiement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('IDENTITY', "Pièce d'identité (CNI / passeport)"), ('PHOTO', 'Photo-signature numérique (ePhoto)'), ('PROOF_ADDRESS', 'Justificatif de domicile'), ('JDC', 'Attestation JDC / recensement'), ('NEPH_CERTIFICATE', 'Attestation NEPH'), ('CONTRACT', 'Contrat de formation signé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Élève'), ('INSTRUCTOR', 'Moniteur / Formateur'), ('SUPERVISOR', 'Superviseur / Bénévole'), ('ADMIN', "Administrateur / gestionnaire d'exploitation"), ('OWNER', 'Super admin (gérant)')], default='STUDENT', max_length=20),
        ),
    ]
