# Generated by Django 4.2.13 on 2026-10-09 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_promote_admins_and_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='etg_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Inscription à l'examen du code (ETG) validée le"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='etg_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
