# Generated by Django 4.2.13 on 2026-10-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_etg_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='billing_interval_months',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Abonnement : prélèvement tous les N mois'),
        ),
        migrations.AddField(
            model_name='offer',
            name='includes_exams',
            field=models.BooleanField(default=False, verbose_name='Accès aux examens blancs'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_addon',
            field=models.BooleanField(default=False, verbose_name='Option ajoutable à une formule (configurateur élève)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='lets_student_pick_skills',
            field=models.BooleanField(default=False, verbose_name="L'élève choisit les compétences à travailler"),
        ),
        migrations.AddField(
            model_name='offer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='offers', to='core.competency', verbose_name='Compétences ciblées (perfectionnement)'),
        ),
        migrations.AddField(
            model_name='package',
            name='installments_paid',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Échéances réglées'),
        ),
        migrations.AddField(
            model_name='package',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='core.package', verbose_name='Formule de base (si option)'),
        ),
        migrations.AddField(
            model_name='package',
            name='requested_skills',
            field=models.JSONField(blank=True, default=list, verbose_name="Compétences choisies par l'élève (codes REMC)"),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('IDENTITY', "Pièce d'identité (CNI / passeport)"), ('PHOTO', 'Photo-signature numérique (ePhoto)'), ('PROOF_ADDRESS', 'Justificatif de domicile'), ('JDC', 'Attestation JDC / recensement'), ('ASSR2', 'ASSR 2 (ou ASR)'), ('NEPH_CERTIFICATE', 'Attestation NEPH'), ('CONTRACT', 'Contrat de formation signé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('PERMIS_B', 'Permis B'), ('CODE', 'Code seul'), ('EXAMS', 'Examens blancs'), ('PERFECTIONNEMENT', 'Perfectionnement / remise en selle'), ('RECHARGE', "Recharge d'heures"), ('OPTION', 'Option (à ajouter à une formule)')], default='PERMIS_B', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='includes_lms',
            field=models.BooleanField(default=False, verbose_name='Accès cours de code / quiz (LMS)'),
        ),
    ]
