# Generated by Django 4.2.13 on 2026-10-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_offer_engine_bundles_assr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='also_instructor',
            field=models.BooleanField(default=False, help_text='Pour un gérant / gestionnaire qui donne des leçons', verbose_name='Enseigne aussi (planning, disponibilités, bilans)'),
        ),
    ]
