# Generated by Django 4.2.13 on 2026-10-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_also_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='meeting_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='core.meetingpoint', verbose_name='Point de rendez-vous (vide = à convenir)'),
        ),
    ]
