# Generated by Django 4.2.13 on 2026-10-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_slot_meeting_point_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='meeting_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='core.meetingpoint', verbose_name='Lieu de prise en charge'),
        ),
    ]
