# Generated by Django 4.2.13 on 2026-10-09 22:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_availability_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='slot',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="Frais d'annulation appliqués (€)"),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_hours', models.PositiveIntegerField(default=48, verbose_name="Préavis d'annulation gratuite (heures avant la leçon)")),
                ('late_penalty', models.CharField(choices=[('DEBIT_HOUR', "L'heure est décomptée du solde"), ('FEE', "Frais d'annulation (l'heure est restituée)"), ('DEBIT_AND_FEE', "Heure décomptée + frais d'annulation"), ('NONE', 'Aucune pénalité')], default='DEBIT_HOUR', max_length=15, verbose_name="Pénalité en cas d'annulation tardive")),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Frais d'annulation tardive (€)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Règles d'annulation",
            },
        ),
    ]
